name: Hot Push

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Weibo Hot
        run: |
          curl -s "https://api.52vmy.cn/api/wl/hot?type=weibo" > weibo.json
          cat weibo.json
          
      - name: Send Test Message
        run: |
          curl "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send?title=测试消息&desp=工作流运行成功"
